import type { CaseStudyDoc, WithId } from "@/lib/types";

// TEMP DEMO DATA — hardcoded so the homepage section has something to show
// before real case studies are seeded in Firestore. Images are seeded
// picsum.photos placeholders (see the remotePatterns note in next.config.ts).
// Remove this file once content is authored in Firestore.
const DEMO_TIMESTAMP = { toDate: () => new Date(), seconds: 0, nanoseconds: 0 };
const DEMO_SEO = { title: "", description: "", ogTitle: "", ogDescription: "", ogImage: "", canonical: "", noindex: true };

export const DEMO_CASE_STUDIES: WithId<CaseStudyDoc>[] = [
  {
    id: "demo-1",
    slug: "demo-aerospace-turbine-blade",
    title: "Aerospace turbine blade finishing",
    industryId: "aerospace",
    challenge: "Micro-burrs on turbine blade edges were affecting fatigue inspection and surface reliability.",
    solution: "Applied MMP treatment to uniformly deburr and polish critical edges.",
    process: "3-stage MMP cycle with in-process surface roughness verification.",
    result: "Reduced surface roughness, improved fatigue performance, consistent finish quality.",
    results: [
      { label: "Surface roughness", value: "Improved", direction: "down" },
      { label: "Fatigue performance", value: "Enhanced", direction: "up" },
      { label: "Finish quality", value: "Consistent", direction: "check" },
    ],
    beforeImage: "https://picsum.photos/seed/infini-cs-turbine-before/1200/900",
    afterImage: "https://picsum.photos/seed/infini-cs-turbine-after/1200/900",
    gallery: [],
    specs: { material: "Inconel 718", process: "MMP Deburring", duration: "48 hrs" },
    seo: DEMO_SEO,
    published: true,
    publishedAt: DEMO_TIMESTAMP,
  },
  {
    id: "demo-2",
    slug: "demo-medical-implant-mirror-finish",
    title: "Medical implant mirror finish",
    industryId: "medical-implants",
    challenge: "Orthopedic implant surfaces required an ultra-consistent finish for demanding medical applications.",
    solution: "MMP mirror-finish process applied to complex implant geometries.",
    process: "Multi-pass MMP polishing with roughness measurement between passes.",
    result: "Improved surface consistency, reduced surface roughness, improved finishing quality.",
    results: [
      { label: "Surface consistency", value: "Improved", direction: "up" },
      { label: "Surface roughness", value: "Reduced", direction: "down" },
      { label: "Finishing quality", value: "Improved", direction: "check" },
    ],
    beforeImage: "https://picsum.photos/seed/infini-cs-implant-before/1200/900",
    afterImage: "https://picsum.photos/seed/infini-cs-implant-after/1200/900",
    gallery: [],
    specs: { material: "Titanium Ti-6Al-4V", process: "MMP Mirror Finish", duration: "36 hrs" },
    seo: DEMO_SEO,
    published: true,
    publishedAt: DEMO_TIMESTAMP,
  },
  {
    id: "demo-3",
    slug: "demo-gear-surface-validation",
    title: "Transmission gear surface validation",
    industryId: "gears-transmission",
    challenge: "Transmission gears showed inconsistent surface finish across production batches.",
    solution: "Standardized MMP treatment with batch-level validation reporting.",
    process: "Automated MMP line with per-batch surface roughness sampling.",
    result: "Improved consistency, reduced friction, improved surface quality.",
    results: [
      { label: "Consistency", value: "Improved", direction: "up" },
      { label: "Friction", value: "Reduced", direction: "down" },
      { label: "Surface quality", value: "Improved", direction: "check" },
    ],
    beforeImage: "https://picsum.photos/seed/infini-cs-gear-before/1200/900",
    afterImage: "https://picsum.photos/seed/infini-cs-gear-after/1200/900",
    gallery: [],
    specs: { material: "Case-hardened steel", process: "MMP Validation", duration: "24 hrs" },
    seo: DEMO_SEO,
    published: true,
    publishedAt: DEMO_TIMESTAMP,
  },
  {
    id: "demo-4",
    slug: "demo-injection-mold-insert-finishing",
    title: "Injection mold insert finishing after EDM",
    industryId: "plastic-injection-molds",
    challenge: "EDM recast layer on cavity inserts was transferring texture to molded parts and slowing ejection.",
    solution: "MMP treatment tuned to remove the recast layer without re-cutting the cavity geometry.",
    process: "Repeatable MMP cycle with in-process variation sampling.",
    result: "Improved repeatability, better surface quality, reduced process variation.",
    results: [
      { label: "Repeatability", value: "Improved", direction: "up" },
      { label: "Surface quality", value: "Better", direction: "check" },
      { label: "Process variation", value: "Reduced", direction: "down" },
    ],
    beforeImage: "https://picsum.photos/seed/infini-cs-industrial-before/1200/900",
    afterImage: "https://picsum.photos/seed/infini-cs-industrial-after/1200/900",
    gallery: [],
    specs: { material: "P20 tool steel", process: "MMP Finishing", duration: "30 hrs" },
    seo: DEMO_SEO,
    published: true,
    publishedAt: DEMO_TIMESTAMP,
  },
  {
    id: "demo-5",
    slug: "demo-carbide-cutting-tool-edge-prep",
    title: "Carbide cutting tool edge preparation",
    industryId: "cutting-tools",
    challenge: "Ground carbide end mills were chipping early under load because of directional micro-roughness at the edge.",
    solution: "Applied MMP treatment calibrated to refine the edge surface without rounding the geometry.",
    process: "Controlled MMP cycle with in-process surface verification.",
    result: "Improved surface quality, consistent finishing, improved tool performance.",
    results: [
      { label: "Surface quality", value: "Improved", direction: "up" },
      { label: "Finishing", value: "Consistent", direction: "check" },
      { label: "Tool life", value: "Extended", direction: "up" },
    ],
    beforeImage: "https://picsum.photos/seed/infini-cs-energy-before/1200/900",
    afterImage: "https://picsum.photos/seed/infini-cs-energy-after/1200/900",
    gallery: [],
    specs: { material: "Tungsten carbide", process: "MMP Finishing", duration: "40 hrs" },
    seo: DEMO_SEO,
    published: true,
    publishedAt: DEMO_TIMESTAMP,
  },
];
